### ISSUE TITLE
Title, redirects, and user-agent

### ISSUE THREAD

**Issue by gpthome** [indix/web-auto-extractor#10]
My team is comparing this package, web-auto-extractor, with node-metainspector and meta-extractor.

TITLE - web-auto-extractor seems to return all the meta tags including og tags, along with the LRMI tags.  Great.  But, it doesn't seem to return some basic HTML elements like 'Title', which is actually important.  Was this intentional?  Perhaps I'm overlooking something.  Perhaps the intent of this package is different than what I'm trying to do.

REDIRECTS - node-metainspector will also follow redirects up to 5 redirects I believe.  This is nice and many sites do actually redirect as their main page changes.  Does web-auto-extractor have the ability to follow redirects?

USER-AGENT - Both other packages allow the user-agent to be set.  Does web-auto-extractor have this ability too?

Thanks.

**Comment by addnab** [comment]
Sorry for the late reply. I guess you must have already found your favorite package by now. I'll answer your questions anyway.

> TITLE - web-auto-extractor seems to return all the meta tags including og tags, along with the LRMI tags. Great. But, it doesn't seem to return some basic HTML elements like 'Title', which is actually important. Was this intentional? Perhaps I'm overlooking something. Perhaps the intent of this package is different than what I'm trying to do.

You are right, capturing `title` is important. When we decided to write this, our main focus was on its ability to parse Schema.org information.

> REDIRECTS - node-metainspector will also follow redirects up to 5 redirects I believe. This is nice and many sites do actually redirect as their main page changes. Does web-auto-extractor have the ability to follow redirects?

> USER-AGENT - Both other packages allow the user-agent to be set. Does web-auto-extractor have this ability too?

web-auto-extractor only takes the HTML as input and doesn't do any fetching. It is fully synchronous. The decision on how you'd want to fetch the page is up to you.
